### PR TITLE
make it build with base==4.14 / ghc-8.8

### PR DESCRIPTION
**Pull request by bfrk**

### CODE REVIEW

**Comment by hsenag** [comment]
Did you build the tests? I get two errors from `src/Tests.hs` (whether or not with your change) with GHC 8.6:

```
src\Tests.hs:97:3: error:
    * No instance for (Control.Monad.Fail.MonadFail CouchMonad)
        arising from a do statement
        with the failable pattern `Just (_, _, v2)'

```

**Comment by bfrk** [comment]
Am 28.06.20 um 13:57 schrieb Ganesh Sittampalam:
> Did you build the tests? I get two errors from `src/Tests.hs` (whether or not with your change) with GHC 8.6:
> 
> ```
> src\Tests.hs:97:3: error:
>     * No instance for (Control.Monad.Fail.MonadFail CouchMonad)
>         arising from a do statement
>         with the failable pattern `Just (_, _, v2)'
> 
> ```
> 

No, forgot about that. Fixed.

I have now done

ben@home[1]:.../darcs/darcsden-upstream>cabal configure -fcli -fposthook
-fssh --constraint 'primitive <0.7.1' --enable-tests

ben@home[1]:.../darcs/darcsden-upstream>cat cabal.project.local
constraints: primitive <0.7.1
flags: +cli +posthook +ssh
tests: True

This seems to enable building the tests for local subprojects, too.

The primitive constraint seems to be necessary, otherwise building the
dependencies fails with ghc-8.2.2.

Anything else I need to set?

Will now start again with ghc-8.2.2.

Sigh
Ben

-- 
...it is impossible to speak of a depoliticized economy as the liberals
do, or of a separation between economic exploitation and political
oppression as the Marxists articulate. The basic distinction, rather, is
between power and creativity...
             -- Jonathan Nitzan and Shimshon Bichler: Capital as Power

**Comment by hsenag** [comment]
The tests for this PR now pass with 8.2.2, 8.6.x and 8.8.3 on Windows, so I think it's good to go. I guess you'd like a release too?

I'm not sure off the top of my head about your general questions about darcsden itself.

**Comment by bfrk** [comment]
Yes, a release would be very nice.

**Comment by hsenag** [comment]
Sorry for the delay, I've pushed a release to hackage now.

I suspect that the previous lax bounds on base will cause trouble everytime someone tries a new GHC (as Cabal will think it can use the older versions) so I'll need to make some hackage revisions at some point. Even the new bounds are too lax on the lower end.
